# Application ArgoCD — PROD
# À appliquer : kubectl apply -f argocd/zenix-app.yaml -n argocd
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zenix-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/emmguardia/Zenix-App-Argo-Repo
    targetRevision: main
    path: charts/zenix-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: zenix-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
