apiVersion: v1
kind: Service
metadata:
  name: zenix-app-backend
  namespace: {{ include "zenix-app.namespace" . }}
  labels:
    {{- include "zenix-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: zenix-app-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
